# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [ ]:
import numpy as np
np.version.version

'2.1.0'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [1]:
import numpy as np
array = np.random.randint(-1000, 1001, size=(10, 10))

min_value = np.min(array)
max_value = np.max(array)

print("Массив 10x10:")
print(array)
print("\nМинимальное значение:" + str(min_value))
print("Максимальное значение:" + str(max_value))

Массив 10x10:
[[-783  305 -200 -850 -433 -538  151  896   94  393]
 [-645  196  183  986 -514 -570 -652 -742   38 -276]
 [ 146 -554 -739  501  517 -449 -584  539  204  461]
 [-161  446 -787 -604 -800 -934  310  701  873 -567]
 [ 742 -401 -813  225  539 -807 -434  984 -877  782]
 [ 692  378  365 -918   94  458 -278  751 -945 -458]
 [-360  500  567 -486 -704  284 -975  731   -6 -199]
 [ 418  664   60 -142 -663  759 -211 -873  532  957]
 [-396  333  -52 -214 -548 -697  817  454  940 -989]
 [-253 -475 -734 -265  -73 -408 -221   50 -518    5]]

Минимальное значение:-989
Максимальное значение:986


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [2]:
import numpy as np
chessboard = np.zeros((8, 8), dtype=int)
for i in range(8):
    for j in range(8):
        if (i + j) % 2 != 0:
            chessboard[i,j]=1
print("Шахматная доска 8x8:")
for row in chessboard:
    print(row)

Шахматная доска 8x8:
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [3]:
z = np.arange(11)
for i in range(len(z)):
  if 3< z[i]< 8:
    z[i]*=-1
print(z)
import numpy as np
z = np.arange(11)
z[(z > 3) & (z < 8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [4]:
import numpy as np
z = np.random.rand(5, 10)
z_centered = z - z.mean(axis=1, keepdims=True)

print("Исходная матрица:")
print(z)
print("\nИтоговая матрица:")
print(z_centered)

Исходная матрица:
[[0.71870664 0.20991137 0.47012852 0.79054718 0.41667463 0.08365546
  0.98587986 0.02318279 0.37516875 0.37825925]
 [0.74900634 0.45246206 0.55925574 0.99483374 0.71105765 0.45951822
  0.18252695 0.27290758 0.49777425 0.32720671]
 [0.69576018 0.16805567 0.75174016 0.34449737 0.65702992 0.04754117
  0.6032703  0.60530446 0.25606014 0.1180216 ]
 [0.74315542 0.93011013 0.06071979 0.38120773 0.34933568 0.19375269
  0.57938008 0.37867663 0.68553384 0.42770908]
 [0.48848803 0.19328992 0.98115491 0.04581603 0.89792959 0.53587902
  0.88352993 0.89300225 0.7490254  0.61115857]]

Итоговая матрица:
[[ 0.2734952  -0.23530008  0.02491707  0.34533574 -0.02853681 -0.36155598
   0.54066842 -0.42202865 -0.07004269 -0.0669522 ]
 [ 0.22835141 -0.06819286  0.03860081  0.47417881  0.19040273 -0.0611367
  -0.33812798 -0.24774734 -0.02288067 -0.19344821]
 [ 0.27103208 -0.25667242  0.32701207 -0.08023073  0.23230182 -0.37718693
   0.1785422   0.18057637 -0.16866796 -0.30670649]
 [ 0.27019732

5. Поменяйте 1 и 2 строки матрицы

In [5]:
import numpy as np
z = np.arange(25).reshape(5,5)
z_swapped = z.copy()
z_swapped[0] = z[1]
z_swapped[1] = z[0]
print("Исходная матрица:")
print(z)
print("Матрица с переставленными строками:")
print(z_swapped)

Исходная матрица:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Матрица с переставленными строками:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [6]:
import numpy as np
z = np.random.random((10, 2))
x = z[:, 0]
y = z[:, 1]
r = np.sqrt(x**2 + y**2)
phi = np.arctan2(y, x)
polar_coords = np.column_stack((r, phi))
print("Декартовы координаты:")
print(z)
print("\nПолярные координаты (радиус, угол в радианах):")
print(polar_coords)

Декартовы координаты:
[[0.69708389 0.98759681]
 [0.33687547 0.43122205]
 [0.57095247 0.40333612]
 [0.72449475 0.77566072]
 [0.82629144 0.84198556]
 [0.30376093 0.42566695]
 [0.67256577 0.39920615]
 [0.05059339 0.08236351]
 [0.86945061 0.5428997 ]
 [0.58676079 0.95586132]]

Полярные координаты (радиус, угол в радианах):
[[1.20883142 0.95616262]
 [0.54720887 0.90761746]
 [0.69904703 0.61502624]
 [1.06138692 0.81949206]
 [1.17970218 0.79480527]
 [0.52293695 0.95099326]
 [0.78211908 0.53566856]
 [0.09666147 1.01995061]
 [1.025029   0.55817993]
 [1.12158775 1.02025116]]


7. Заменить максимальный элемент массива на ноль

In [7]:
import numpy as np

z = np.random.random(10)
print("Исходный массив:")
print(z)
max_index = np.argmax(z)
z[max_index] = 0

print("Массив после замены максимального элемента:")
print(z)

Исходный массив:
[0.05622676 0.54833511 0.8499034  0.91790405 0.77098666 0.67040594
 0.46660162 0.33591236 0.34949799 0.54195774]
Массив после замены максимального элемента:
[0.05622676 0.54833511 0.8499034  0.         0.77098666 0.67040594
 0.46660162 0.33591236 0.34949799 0.54195774]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [8]:
import numpy as np
z = np.ones(10)
print("Первый массив:", z)
i = np.random.randint(0, len(z), 20)
unique_indices = np.unique(i)
z[unique_indices] += 1
print("Массив индексов i:", i)
print("Массив без повторений:", unique_indices)
print("Результат:")
print(z)

Первый массив: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Массив индексов i: [1 5 3 2 6 0 5 9 6 2 2 5 1 1 8 8 7 4 3 5]
Массив без повторений: [0 1 2 3 4 5 6 7 8 9]
Результат:
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [9]:
import numpy as np
z = np.array([1, 2, 3, 4, 5])
new_length = len(z) + (len(z) - 1) * 3
result = np.zeros(new_length, dtype=z.dtype)
result[::4] = z
print(result)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


10. Найти ближайшее к заданному значению число в заданном массиве

In [10]:
import numpy as np
z = np.arange(100)  # Массив чисел от 0 до 99
v = np.random.uniform(0, 100)  # Случайное число от 0 до 100
idx = (np.abs(z - v)).argmin()
nearest_value = z[idx]
print(f"Случайное число v: {v}")
print(f"Ближайшее число в массиве z: {nearest_value}")

Случайное число v: 41.476241585906884
Ближайшее число в массиве z: 41


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])
np.array([1., 4, 2, 5, 3])
np.array([1, 4, 2, 5, 3], dtype='float128')
np.array([1., 4, 2, 5, 3], dtype='complex128')
np.array([1, 4, 2, 5, 3], dtype ='float64')
np.array([1, 4, 2, 5, 3], dtype =int64)
np.array([1, 4, 2, 5, 3], dtype='bool')
np.array([1, 4, 2, 5, 3], dtype='str')
np.array([1, 4, 2, 5, '3'])
np.array([1, -4, 2, 0, 1j])
```

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)
np.linspace(0, 1, 5)
np.diag((1,3,5))
np.smile((1,3,5))
np.random.random((3, 3))
np.eye(3)
np.empty(3)
```



**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])
np.split(grid, [2], axis=1)
```


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]
    np.array([1, 2, 3]) + np.array([3, 2, 1])
```

**7**. Как в CodeLab измерить время выполнения кода?

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M)
np.sum(M, axis=1)
np.sum(M, axis=0)
np.sum(M, axis=2)
np.sum(M, 1)
sum(M)
sum(M,1)
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3
X < 3
X[X < 3]
X[X > 3]
X[X != 3]
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?